### PR TITLE
new feature - add

### PR DESCRIPTION
**Pull request by SpatzieB**
Added add function and its test

### CODE REVIEW

**Review by etomoscow — COMMENTED** [review]
Everything is ok. Add test when adding existing value.

**Comment by daleschyov** [comment]
Add realisation is ok
The second test for adding value for existing key will raise KeyError and code won't proceed further
Maybe it is better to use "try except KeyError" construction to check, if an error occurs without stopping the code

**Comment by SpatzieB** [comment]
> Add realisation is ok
> The second test for adding value for existing key will raise KeyError and code won't proceed further
> Maybe it is better to use "try except KeyError" construction to check, if an error occurs without stopping the code

Changed test with the existing key.

**Comment by etomoscow** [comment]
Updates reviewed. Merging.

**Pull request merged**
